/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Loop forever */
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;//0x40021000 [BASE] + 0x14 [OFFSET]
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;//0x48001000 [BASE] + 0x00 [OFFSET]
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;//0x48001000 [BASE] + 0x14 [OFFSET]
	uint32_t *pPortAInReg =   (uint32_t*)0x40020010;
	uint32_t *pPortAModeReg = (uint32_t*)0x40020000;




int main(void)
{
//    /* Loop forever */
//	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;//0x40021000 [BASE] + 0x14 [OFFSET]
//	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;//0x48001000 [BASE] + 0x00 [OFFSET]
//	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;//0x48001000 [BASE] + 0x14 [OFFSET]
//	uint32_t volatile *const pPortAInReg =   (uint32_t*)0x40020C10;

	//*pPortAInReg = 0;
	//1. enable the clock for GPOIE peripheral in the AHBENR (SET the 21st bit position)
	*pClkCtrlReg |= ( 1 << 3);
	*pClkCtrlReg |= ( 1 << 0);

	//2. configure the mode of the IO pin 8 as output
	//a. clear the 16th and 17th bit positions (CLEAR)
	*pPortDModeReg &= ~( 1 << 26);
	//b. make 16th bit position as 1 (SET)
	*pPortDModeReg |= ( 1 << 26);

	*pPortAModeReg &= ~( 3 << 0);


		static uint8_t lastState = 1;
		uint8_t currentState = 0;
//	    static uint8_t ledState = 0;





	//3.SET 8th bit of the output data register to make I/O pin-8 as HIGH
	//*pPortEOutReg |= ( 1 << 12);

	while(1)
	{
		if((uint8_t)(*pPortAInReg & (0x01)))
		{
			for(uint8_t i = 0; i < 50; i++);
			if((uint8_t)(*pPortAInReg & (0x01)))
			{
				currentState++;
			}
		}

		if ((currentState%2 == 0x01) && lastState == 1)
		{

			*pPortDOutReg |= (1 << 13);
			lastState = 0;
			// Button pressed
			//_delay_ms(50); // Debounce
//			if ((*pPortAInReg & (1 << *pPortAInReg)) == 0)
//			{
//				ledState = !ledState; // Toggle state
//				if (ledState) *pPortDOutReg |= (1 << 13); // LED ON
//				else if (ledState == 0) *pPortDOutReg &= ~(1 << 13);         // LED OFF
//			}
		}
		else if ((currentState%2 == 0x00) && lastState == 0)
		{
			*pPortDOutReg &= ~(1 << 13);         // LED OFF
			lastState = 1;
		}
		else
		{

		}
//		lastState = currentState;


		//3.read the pin status of the pin PA0 (GPIOA INPUT DATA REGISTER)
				/*uint8_t  pinStatus = (uint8_t)(*pPortAInReg & (1 << 0)); //zero out all other bits except bit 0

				if(pinStatus & 0x1){
					//turn on the LED
					*pPortDOutReg |= ( 1 << 13);
				}else{
					//turn off the LED
					*pPortDOutReg &= ~(1 << 13);
				}*/


		}
	}

